name: Sokobanja_Daily_Bot
on:
  schedule:
    - cron: '0 19 * * *' # Ovo pokreće bota svako veče u 20:00h po našem vremenu
  workflow_dispatch: # Ovo ti daje dugme da bota pokreneš "na silu" kad god poželiš
jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalacija Python biblioteka
        run: pip install requests google-generativeai
      - name: Pokretanje bota
        env:
          GEMINI_API_KEY: ${{ secrets.AIzaSyB2D7jNlfcyJJbry6AMFQTOqG1UomhdfRc }}
          WP_USERNAME: ${{ secrets.aibot }}
          WP_APP_PASSWORD: ${{ secrets.UXWxtBla3Qm(utb3wG!9xsnh }}
        run: python bot.py
